# ۰۰ - فهرست و پروفایل داده‌های خام

این نوتبوک فهرست فیزیکی فایل‌های داده را ثبت می‌کند، تعداد سطر و ستون هر جدول را می‌شمارد و پروفایل ستون‌ها (نوع، مقادیر گمشده، مقادیر یکتا) را تولید می‌کند.

## ۲. سؤال‌های کسب‌وکاری

1. چه فایل‌هایی در دیتاست وجود دارد و حجم هر یک چقدر است؟
2. هر جدول چند سطر و چند ستون دارد؟
3. چه ستون‌هایی مقدار گمشده دارند و درصد آن چقدر است؟
4. آیا ردیف تکراری کامل در جدول‌ها وجود دارد؟

## ۱. عنوان و هدف

این نوتبوک فهرست فیزیکی فایل‌های داده را ثبت می‌کند، تعداد سطر و ستون هر جدول را می‌شمارد و پروفایل ستون‌ها (نوع، مقادیر گمشده، مقادیر یکتا) را تولید می‌کند.

In [1]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import pandas as pd
from IPython.display import Image, display

from olist_analysis import metrics as M
from olist_analysis.config import FIGURES_DIR, REPORTS_DIR, TABLES_DIR
from olist_analysis.font_utils import persian_available
from olist_analysis.features import load_dataset
from olist_analysis.pipeline import load_headline

pd.set_option("display.width", 200)
pd.set_option("display.max_columns", 60)

ds = load_dataset()
headline = load_headline()
print("Persian font registered for charts:", persian_available())
print(f"orders={len(ds.orders):,}  items={len(ds.items):,}  "
      f"delivered={len(ds.delivered):,}  reviewed={len(ds.reviews_per_order):,}")

Persian font registered for charts: True
orders=99,441  items=112,650  delivered=96,470  reviewed=98,673

## ۳. داده‌ها و ستون‌های مورد استفاده

۹ فایل CSV در `data/raw/`. فهرست کامل و اثر انگشت SHA-256 کوتاه هر فایل در جدول `01_file_inventory` ثبت شده است.

## ۴. روش محاسبه

شمارش سطرها با `pandas.read_csv` انجام می‌شود (ردیف منطقی)، نه با شمارش خطوط فایل؛ چون بعضی نظرات مشتریان در `olist_order_reviews_dataset.csv` شامل خط جدید داخل متن هستند.

In [2]:
display(pd.read_csv(TABLES_DIR / "01_file_inventory.csv"))

                  table                               filename  exists  size_bytes  size_mb         sha256_16
0                orders               olist_orders_dataset.csv    True    17654914    16.84  8df58ef3d2d7e994
1             customers            olist_customers_dataset.csv    True     9033957     8.62  983a422239e1712d
2           order_items          olist_order_items_dataset.csv    True    15438671    14.72  0bc4d068c4fe38cb
3        order_payments       olist_order_payments_dataset.csv    True     5777138     5.51  4f713964f2815dbb
4         order_reviews        olist_order_reviews_dataset.csv    True    14346950    13.68  81336b6e5183133b
5              products             olist_products_dataset.csv    True     2379446     2.27  3e6569628a17fbc7
6               sellers              olist_sellers_dataset.csv    True      174703     0.17  1f643d2b950373b8
7           geolocation          olist_geolocation_dataset.csv    True    61273883    58.44  b514f6fc991b9566
8  category_translation  product_category_name_translation.csv    True        2542     0.00  9da093e114e51753

In [3]:
display(pd.read_csv(TABLES_DIR / "01_table_shapes.csv"))

                  table     rows  columns
0                orders    99441        8
1             customers    99441        5
2           order_items   112650        7
3        order_payments   103886        5
4         order_reviews    99224        7
5              products    32951        9
6               sellers     3095        4
7           geolocation  1000163        5
8  category_translation       71        2

## ۵. بررسی کیفیت داده مرتبط

In [4]:
profiles = pd.read_csv(TABLES_DIR / "00_column_profiles.csv")
display(profiles.head(20))

          table                         column    dtype    rows  non_null  n_missing  pct_missing  n_unique                                      sample_values
0        orders                       order_id      str   99441     99441          0       0.0000     99441  e481f51cbdc54678b7cc49136f2d6af7 | 53cdb2fc8bc...
1        orders                    customer_id      str   99441     99441          0       0.0000     99441  9ef432eb6251297304e76186b10a928d | b0830fb4747...
2        orders                   order_status      str   99441     99441          0       0.0000         8                     delivered | invoiced | shipped
3        orders       order_purchase_timestamp      str   99441     99441          0       0.0000     98875  2017-10-02 10:56:33 | 2018-07-24 20:41:37 | 20...
4        orders              order_approved_at      str   99441     99281        160       0.1609     90733  2017-10-02 11:07:15 | 2018-07-26 03:24:27 | 20...
5        orders   order_delivered_carrier_date      str   99441     97658       1783       1.7930     81018  2017-10-04 19:55:00 | 2018-07-26 14:31:00 | 20...
6        orders  order_delivered_customer_date      str   99441     96476       2965       2.9817     95664  2017-10-10 21:25:13 | 2018-08-07 15:27:45 | 20...
7        orders  order_estimated_delivery_date      str   99441     99441          0       0.0000       459  2017-10-18 00:00:00 | 2018-08-13 00:00:00 | 20...
8     customers                    customer_id      str   99441     99441          0       0.0000     99441  06b8999e2fba1a1fbc88172c00ba8bc7 | 18955e83d33...
9     customers             customer_unique_id      str   99441     99441          0       0.0000     96096  861eff4711a542e4b93843c6dd7febb0 | 290c77bc529...
10    customers       customer_zip_code_prefix    int64   99441     99441          0       0.0000     14994                                14409 | 9790 | 1151
11    customers                  customer_city      str   99441     99441          0       0.0000      4119         franca | sao bernardo do campo | sao paulo
12    customers                 customer_state      str   99441     99441          0       0.0000        27                                       SP | SC | MG
13  order_items                       order_id      str  112650    112650          0       0.0000     98666  00010242fe8c5a6d1ba2dd792cb16214 | 00018f77f2f...
14  order_items                  order_item_id    int64  112650    112650          0       0.0000        21                                          1 | 2 | 3
15  order_items                     product_id      str  112650    112650          0       0.0000     32951  4244733e06e7ecb4970a6e2683c13e61 | e5f2d52b802...
16  order_items                      seller_id      str  112650    112650          0       0.0000      3095  48436dade18ac8b2bce089ec2a041202 | dd7ddc04e1b...
17  order_items            shipping_limit_date      str  112650    112650          0       0.0000     93318  2017-09-19 09:45:35 | 2017-05-03 11:05:13 | 20...
18  order_items                          price  float64  112650    112650          0       0.0000      5968                               58.9 | 239.9 | 199.0
19  order_items                  freight_value  float64  112650    112650          0       0.0000      6999                              13.29 | 19.93 | 17.87

In [5]:
missing = pd.read_csv(TABLES_DIR / "00_missing_values.csv")
display(missing)

            table                         column  n_missing  pct_missing
0          orders  order_delivered_customer_date       2965       2.9817
1          orders   order_delivered_carrier_date       1783       1.7930
2          orders              order_approved_at        160       0.1609
3   order_reviews           review_comment_title      87656      88.3415
4   order_reviews         review_comment_message      58247      58.7025
5        products          product_category_name        610       1.8512
6        products            product_name_lenght        610       1.8512
7        products     product_description_lenght        610       1.8512
8        products             product_photos_qty        610       1.8512
9        products               product_weight_g          2       0.0061
10       products              product_length_cm          2       0.0061
11       products              product_height_cm          2       0.0061
12       products               product_width_cm          2       0.0061

In [6]:
display(pd.read_csv(TABLES_DIR / "00_duplicate_rows.csv"))

                  table     rows  duplicate_rows_all_columns  pct_duplicate_rows
0                orders    99441                           0              0.0000
1             customers    99441                           0              0.0000
2           order_items   112650                           0              0.0000
3        order_payments   103886                           0              0.0000
4         order_reviews    99224                           0              0.0000
5              products    32951                           0              0.0000
6               sellers     3095                           0              0.0000
7           geolocation  1000163                      261831             26.1788
8  category_translation       71                           0              0.0000

In [7]:
display(pd.read_csv(TABLES_DIR / "00_key_uniqueness.csv"))

                  table                           key           status   n_rows  n_distinct  n_duplicated_keys  n_rows_on_duplicate_keys  n_null_in_key
0                orders                      order_id           UNIQUE    99441     99441.0                0.0                       0.0            0.0
1             customers                   customer_id           UNIQUE    99441     99441.0                0.0                       0.0            0.0
2           order_items       order_id, order_item_id           UNIQUE   112650    112650.0                0.0                       0.0            0.0
3        order_payments  order_id, payment_sequential           UNIQUE   103886    103886.0                0.0                       0.0            0.0
4         order_reviews                     review_id       NOT_UNIQUE    99224     98410.0              789.0                    1603.0            0.0
5              products                    product_id           UNIQUE    32951     32951.0                0.0                       0.0            0.0
6               sellers                     seller_id           UNIQUE     3095      3095.0                0.0                       0.0            0.0
7           geolocation               (none declared)  NO_DECLARED_KEY  1000163         NaN                NaN                       NaN            NaN
8  category_translation         product_category_name           UNIQUE       71        71.0                0.0                       0.0            0.0

## ۸. یافته‌های واقعی

- مجموع حجم داده خام ۱۲۰.۲۵ مگابایت است؛ بزرگ‌ترین فایل، جدول ژئولوکیشن با ۵۸.۴۴ مگابایت و ۱٬۰۰۰٬۱۶۳ سطر است.
- جدول نظرات ۹۹٬۲۲۴ **ردیف منطقی** دارد در حالی که فایل آن ۱۰۴٬۷۲۰ خط فیزیکی است (متن بعضی نظرات شامل خط جدید است).
- `review_id` به‌عنوان کلید اصلی اعلام شده اما یکتا نیست: ۷۸۹ شناسه تکرار شده و ۱٬۶۰۳ سطر را در بر می‌گیرد.
- جدول ژئولوکیشن ۲۶۱٬۸۳۱ سطر کاملاً تکراری دارد و کلید اصلی اعلام‌شده ندارد.
- هیچ ردیف تکراری کاملی در ۸ جدول دیگر وجود ندارد.

## ۱۰. محدودیت‌های تحلیل

در این مرحله هیچ داده‌ای اصلاح یا حذف نمی‌شود؛ فقط شواهد جمع‌آوری می‌شود. تصمیم‌ها در نوتبوک ۰۲ ثبت شده‌اند.

## ۱۱. نتیجه‌گیری

ساختار داده برای تحلیل چندجدولی مناسب است، اما سه مسئله کیفیت داده باید پیش از تحلیل حل شود: تکرار شناسه نظر، تکرار گسترده در جدول ژئولوکیشن و مقادیر گمشده ساختاری در جدول سفارش‌ها.